/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a set of docs in the sidebar
 - provide next/previous navigation

 The docusaurus community has autogenerated sidebars (~40+) on awesome-docusaurus, so you don't have to.

 You can create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  centralSidebar: [
    'central-app/intro',
    {
      type: 'category',
      label: 'Memulai',
      items: [
        'central-app/memulai',
        'central-app/dasar/trial',
        'central-app/dasar/berlangganan',
      ],
    },
    {
      type: 'category',
      label: 'Autentikasi',
      items: [
        'central-app/autentikasi/registrasi',
        'central-app/autentikasi/masuk',
        'central-app/autentikasi/lupa-kata-sandi',
      ],
    },
    {
      type: 'category',
      label: 'Dasar',
      items: ['central-app/dasar/data-sekolah'],
    },
  ],
  tenantSidebar: [
    'tenant-app/intro',
    {
      type: 'category',
      label: 'Autentikasi',
      items: ['tenant-app/autentikasi/masuk', 'tenant-app/autentikasi/lupa-kata-sandi'],
    },
    {
      type: 'category',
      label: 'Dashboard',
      items: ['tenant-app/user-panel/dashboard'],
    },
    {
      type: 'category',
      label: 'Admin Panel',
      items: [
        'tenant-app/admin-panel/dashboard-admin',
        'tenant-app/admin-panel/pengguna',
        'tenant-app/admin-panel/peran',
        {
          type: 'category',
          label: 'Blog',
          items: [
            'tenant-app/admin-panel/blog/berita',
            'tenant-app/admin-panel/blog/halaman',
            'tenant-app/admin-panel/blog/kategori',
            'tenant-app/admin-panel/blog/tag',
            'tenant-app/admin-panel/blog/slider-gambar',
            'tenant-app/admin-panel/blog/komentar',
          ],
        },
        {
          type: 'category',
          label: 'Tampilan',
          items: [
            'tenant-app/admin-panel/tampilan/menu',
            'tenant-app/admin-panel/tampilan/modul',
            'tenant-app/admin-panel/tampilan/tema',
          ],
        },
        {
          type: 'category',
          label: 'Pengaturan',
          items: [
            'tenant-app/admin-panel/pengaturan/pengaturan-umum',
            'tenant-app/admin-panel/pengaturan/profil-sekolah',
            'tenant-app/admin-panel/pengaturan/pengaturan-server-email',
            {
              type: 'category',
              label: 'Blog',
              items: [
                'tenant-app/admin-panel/pengaturan/blog/pengaturan-membaca',
                'tenant-app/admin-panel/pengaturan/blog/pengaturan-diskusi',
              ],
            },
          ],
        },
      ],
    },
  ],
  helpSidebar: ['help-center/faq', 'help-center/troubleshooting'],
};

module.exports = sidebars;
