/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Cendekia Platform",
  "tagline": "Documentation Portal - PT Cendekia Digital Solusi",
  "favicon": "img/favicon.ico",
  "url": "https://docs.cendekiadigitalsolusi.co.id",
  "baseUrl": "/en/",
  "organizationName": "CendekiaDigitalSolusi",
  "projectName": "docs",
  "headTags": [
    {
      "tagName": "meta",
      "attributes": {
        "name": "algolia-site-verification",
        "content": "4C298CE250841923"
      }
    }
  ],
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "id",
    "locales": [
      "id",
      "en"
    ],
    "localeConfigs": {
      "id": {
        "label": "Bahasa Indonesia",
        "htmlLang": "id-ID"
      },
      "en": {
        "label": "English",
        "htmlLang": "en-US"
      }
    },
    "path": "i18n"
  },
  "themes": [
    [
      "/workspaces/docs/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "indexBlog": false,
        "indexPages": true,
        "docsDir": [
          "gradynex",
          "sso-cendekia"
        ],
        "docsRouteBasePath": [
          "/gradynex",
          "/sso-cendekia"
        ],
        "searchContextByPaths": [
          "gradynex",
          "sso-cendekia"
        ],
        "useAllContextsWithNoSearchContext": true,
        "searchBarPosition": "right"
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "path": "gradynex",
          "routeBasePath": "gradynex",
          "sidebarPath": "/workspaces/docs/sidebars.js"
        },
        "blog": false,
        "theme": {
          "customCss": "/workspaces/docs/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "ssoCds",
        "path": "sso-cendekia",
        "routeBasePath": "sso-cendekia",
        "sidebarPath": "/workspaces/docs/sidebars-sso.js"
      }
    ],
    [
      "@docusaurus/plugin-vercel-analytics",
      {
        "debug": false,
        "mode": "auto"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Cendekia",
      "items": [
        {
          "to": "/",
          "label": "Home",
          "position": "left"
        },
        {
          "label": "SSO Cendekia",
          "position": "left",
          "to": "/sso-cendekia/",
          "items": [
            {
              "label": "User Guide",
              "to": "/sso-cendekia/"
            },
            {
              "label": "Sign In",
              "to": "/sso-cendekia/pengguna/masuk"
            },
            {
              "label": "Forgot Password",
              "to": "/sso-cendekia/pengguna/lupa-kata-sandi"
            },
            {
              "label": "FAQ",
              "to": "/sso-cendekia/pengguna/faq"
            }
          ]
        },
        {
          "label": "Gradynex",
          "position": "left",
          "to": "/gradynex",
          "items": [
            {
              "label": "Overview",
              "to": "/gradynex"
            },
            {
              "label": "Central App",
              "to": "/gradynex/central-app/intro"
            },
            {
              "label": "Tenant App",
              "to": "/gradynex/tenant-app/intro"
            },
            {
              "label": "Help Center",
              "to": "/gradynex/help-center/faq"
            }
          ]
        },
        {
          "href": "https://cendekiadigitalsolusi.co.id/",
          "label": "Website",
          "position": "right"
        },
        {
          "type": "search",
          "position": "right"
        },
        {
          "type": "localeDropdown",
          "position": "right",
          "dropdownItemsBefore": [],
          "dropdownItemsAfter": []
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Central App",
              "to": "/gradynex/central-app/intro"
            },
            {
              "label": "Tenant App",
              "to": "/gradynex/tenant-app/intro"
            },
            {
              "label": "SSO Cendekia",
              "to": "/sso-cendekia/"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Website",
              "href": "https://cendekiadigitalsolusi.co.id/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 PT Cendekia Digital Solusi."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
